import { readdirSync } from 'node:fs';
import { defineConfig } from 'drizzle-kit';

// Used only by `drizzle-kit studio`, against the local D1 database that
// `bun run db:migrate` creates. Migrations are hand-written SQL in
// db/migrations, applied by wrangler — not generated by drizzle-kit.
const LOCAL_D1_DIR = '.wrangler/state/v3/d1/miniflare-D1DatabaseObject';
const localDb = readdirSync(LOCAL_D1_DIR).find((file) => file.endsWith('.sqlite'));

export default defineConfig({
  schema: './db/schema.ts',
  dialect: 'sqlite',
  dbCredentials: { url: `${LOCAL_D1_DIR}/${localDb}` },
});
