#!/usr/bin/env node
/**
 * Generate service worker with embedded version from version.ts
 * Run during build to ensure service worker cache matches build version
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read the generated version info
const versionPath = join(__dirname, '../src/lib/version.ts');
const versionContent = readFileSync(versionPath, 'utf8');

// Extract version and commitHash using regex
const versionMatch = versionContent.match(/version: '([^']+)'/);
const commitHashMatch = versionContent.match(/commitHash: '([^']+)'/);

const version = versionMatch ? versionMatch[1] : 'unknown';
const commitHash = commitHashMatch ? commitHashMatch[1] : 'unknown';

// Use commitHash as the cache version (it's unique per build)
const cacheVersion = commitHash;

// Service worker template
const serviceWorkerContent = `/**
 * Service Worker for PackZen PWA
 * Auto-generated by scripts/generate-sw.js
 * Version: ${version} (${commitHash})
 */

const CACHE_VERSION = '${cacheVersion}';
const CACHE_NAME = \`packzen-\${CACHE_VERSION}\`;

// Files to cache immediately on install
const PRECACHE_URLS = [
  '/',
  '/dashboard',
  '/trips',
  '/all-items',
  '/manifest.json',
  '/favicon.png',
  '/logo.png',
];

// Install event - cache essential resources
self.addEventListener('install', (event) => {
  console.log('Installing service worker version:', CACHE_VERSION);
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(PRECACHE_URLS).catch((err) => {
        console.error('Failed to cache some resources:', err);
      });
    })
  );
  // Activate immediately
  self.skipWaiting();
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
  console.log('Activating service worker version:', CACHE_VERSION);
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name.startsWith('packzen-') && name !== CACHE_NAME)
          .map((name) => {
            console.log('Deleting old cache:', name);
            return caches.delete(name);
          })
      );
    })
  );
  // Take control immediately
  self.clients.claim();
});

// Fetch event - network first, fallback to cache
self.addEventListener('fetch', (event) => {
  // Skip non-GET requests
  if (event.request.method !== 'GET') {
    return;
  }

  // Skip chrome extensions and other origins
  if (!event.request.url.startsWith(self.location.origin)) {
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((response) => {
        // Clone the response before caching
        const responseToCache = response.clone();

        // Cache successful responses
        if (response.status === 200) {
          caches.open(CACHE_NAME).then((cache) => {
            cache.put(event.request, responseToCache);
          });
        }

        return response;
      })
      .catch(() => {
        // Network failed, try cache
        return caches.match(event.request).then((cachedResponse) => {
          if (cachedResponse) {
            return cachedResponse;
          }

          // For navigation requests, return cached homepage as fallback
          if (event.request.mode === 'navigate') {
            return caches.match('/');
          }

          // Return a basic offline response for other requests
          return new Response('Offline', {
            status: 503,
            statusText: 'Service Unavailable',
            headers: new Headers({
              'Content-Type': 'text/plain',
            }),
          });
        });
      })
  );
});
`;

// Write the generated service worker
const outputPath = join(__dirname, '../public/sw.js');
writeFileSync(outputPath, serviceWorkerContent, 'utf8');

console.log(`✓ Generated service worker with cache version: ${cacheVersion}`);
