#!/usr/bin/env node
/**
 * Generate dist/sw.js after `astro build`. The cache name is a hash of the
 * precached files' contents, so it changes exactly when what's cached does.
 */

import { createHash } from 'crypto';
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, relative, sep } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Base app-shell routes cached immediately on install. `/dashboard/`,
// `/trips/`, and `/all-items/` are safe here even though they're
// "logged-in" pages: they're static-output Astro pages with a purely
// client-side auth gate (a script that redirects to /sign-in if
// unauthenticated) — the built HTML is identical for every visitor, so
// there's no risk of precaching a server-baked redirect for someone else's
// session.
const BASE_PRECACHE_URLS = [
  '/',
  '/dashboard/',
  '/trips/',
  '/all-items/',
  '/sign-in/',
  '/sign-up/',
  '/manifest.json',
  '/favicon.png',
  '/logo.png',
];

/**
 * Recursively collect hashed build assets under dist/_astro so a
 * first-ever offline visit has real JS/CSS to run against instead of a
 * dead HTML shell. Astro fingerprints these filenames per build, so they
 * can only be discovered by scanning actual build output — there's no
 * pre-build manifest to read.
 *
 * The `build` script runs `sw:generate` after `astro build`, so dist/ holds
 * this build's freshly-hashed assets when this runs.
 *
 * @param {string} distDir
 * @returns {string[]}
 */
export function findPrecacheAssetPaths(distDir) {
  const astroDir = join(distDir, '_astro');
  if (!existsSync(astroDir)) return [];

  const assetExtensions = /\.(js|css)$/i;
  /** @type {string[]} */
  const paths = [];

  function walk(dir) {
    for (const entry of readdirSync(dir)) {
      const fullPath = join(dir, entry);
      if (statSync(fullPath).isDirectory()) {
        walk(fullPath);
      } else if (assetExtensions.test(entry)) {
        const relPath = relative(astroDir, fullPath).split(sep).join('/');
        paths.push(`/_astro/${relPath}`);
      }
    }
  }

  walk(astroDir);
  return paths;
}

/**
 * @param {string[]} precacheAssets hashed /_astro paths
 * @returns {string[]} every URL the service worker precaches
 */
export function precacheUrlsFor(precacheAssets) {
  return [...BASE_PRECACHE_URLS, ...precacheAssets];
}

/**
 * Short content hash of the files behind `urls` in `distDir` (a URL ending in
 * `/` is its index.html; missing files contribute just their URL).
 *
 * @param {string} distDir
 * @param {string[]} urls
 * @returns {string}
 */
export function computeCacheVersion(distDir, urls) {
  const hash = createHash('sha256');
  for (const url of urls) {
    const file = join(distDir, url.endsWith('/') ? `${url}index.html` : url);
    hash.update(url).update('\0');
    if (existsSync(file)) hash.update(readFileSync(file));
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 12);
}

/**
 * Build the full service worker source as a string. Pure function of its
 * inputs so it can be unit-tested without touching the filesystem.
 *
 * @param {{ version: string, cacheVersion: string, precacheAssets?: string[] }} options
 * @returns {string}
 */
export function buildServiceWorkerSource({ version, cacheVersion, precacheAssets = [] }) {
  const precacheUrlsLiteral = JSON.stringify(precacheUrlsFor(precacheAssets), null, 2);

  return `/**
 * Service Worker for PackZen PWA
 * Auto-generated by scripts/generate-sw.js
 * App version: ${version}
 */

const CACHE_VERSION = '${cacheVersion}';
const CACHE_NAME = \`packzen-\${CACHE_VERSION}\`;

// Files to cache immediately on install: base app-shell routes plus the
// hashed /_astro/* bundle files produced by the build.
const PRECACHE_URLS = ${precacheUrlsLiteral};

// Install event - cache essential resources
self.addEventListener('install', (event) => {
  console.log('Installing service worker version:', CACHE_VERSION);
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(PRECACHE_URLS).catch((err) => {
        // cache.addAll is all-or-nothing: a single missing/failed URL
        // aborts the whole precache. Surface that loudly rather than
        // silently installing with an empty (or partial) cache.
        console.error('Precache failed - service worker installed with no precached assets:', err);
      });
    })
  );
  // Activate immediately
  self.skipWaiting();
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
  console.log('Activating service worker version:', CACHE_VERSION);
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => name.startsWith('packzen-') && name !== CACHE_NAME)
          .map((name) => {
            console.log('Deleting old cache:', name);
            return caches.delete(name);
          })
      );
    })
  );
  // Take control immediately
  self.clients.claim();
});

// Fetch event - cache-first for static assets, network-first (no
// artificial timeout) for everything else. Requests we don't handle (other
// origins, non-GETs, sync polls) get no respondWith, so the browser sends
// them exactly as it would without a service worker.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin || event.request.method !== 'GET') {
    return;
  }

  // Pass through SSE sync requests — EventSource manages its own connection
  if (url.pathname === '/api/sync/events') {
    return;
  }

  // Use cache-first for static assets (CSS, JS, images, fonts)
  const isStaticAsset = /\\.(css|js|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$/i.test(url.pathname);

  // /_astro/* filenames are content-hashed, so a cached copy never goes stale.
  const isImmutable = url.pathname.startsWith('/_astro/');

  if (isStaticAsset) {
    // Cache-first strategy for static assets
    event.respondWith(
      caches.match(event.request).then((cachedResponse) => {
        if (cachedResponse) {
          // Return cached version immediately; refresh unhashed files in the background
          if (!isImmutable) fetchAndCache(event.request);
          return cachedResponse;
        }
        // Not in cache, fetch from network
        return fetchAndCache(event.request);
      })
    );
  } else {
    // Network-first for HTML/API GETs. No artificial timeout: a slow but
    // eventually-successful response must win over a synthetic failure —
    // this matters most for API GETs, which are deliberately never cached,
    // so a timed-out request had nothing to fall back to but a fake 503.
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          // Clone and cache successful responses (but not API responses)
          if (response.status === 200 && !url.pathname.startsWith('/api/')) {
            const responseToCache = response.clone();
            caches.open(CACHE_NAME).then((cache) => {
              cache.put(event.request, responseToCache);
            });
          }
          return response;
        })
        .catch(() => {
          // Network genuinely failed (offline, DNS, etc.) - try cache.
          return caches.match(event.request).then((cachedResponse) => {
            if (cachedResponse) {
              return cachedResponse;
            }

            // For navigation requests, try to match with trailing slash or without
            if (event.request.mode === 'navigate') {
              const urlPath = url.pathname;
              const alternateUrl = urlPath.endsWith('/') ? urlPath.slice(0, -1) : urlPath + '/';

              return caches.match(alternateUrl).then((altResponse) => {
                if (altResponse) return altResponse;

                // Final fallback to homepage
                return caches.match('/').then((response) => {
                  return response || new Response(
                    '<!DOCTYPE html><html><head><title>Offline</title></head><body><h1>App is offline</h1><p>Please check your connection and try again.</p></body></html>',
                    { headers: { 'Content-Type': 'text/html' } }
                  );
                });
              });
            }

            // Return a basic offline response for other requests
            return new Response('Offline', {
              status: 503,
              statusText: 'Service Unavailable',
              headers: new Headers({
                'Content-Type': 'text/plain',
              }),
            });
          });
        })
    );
  }
});

// Helper function to fetch and cache
async function fetchAndCache(request) {
  try {
    const response = await fetch(request);
    if (response.status === 200) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch (error) {
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }
    throw error;
  }
}
`;
}

function main() {
  const distDir = join(__dirname, '../dist');
  if (!existsSync(distDir)) {
    throw new Error('generate-sw: dist/ not found; run this after `astro build`.');
  }

  const versionContent = readFileSync(join(__dirname, '../src/lib/version.ts'), 'utf8');
  const version = versionContent.match(/version: '([^']+)'/)?.[1] ?? 'unknown';

  const precacheAssets = findPrecacheAssetPaths(distDir);
  const cacheVersion = computeCacheVersion(distDir, precacheUrlsFor(precacheAssets));
  const serviceWorkerContent = buildServiceWorkerSource({ version, cacheVersion, precacheAssets });
  writeFileSync(join(distDir, 'sw.js'), serviceWorkerContent, 'utf8');

  console.log(
    `✓ Generated service worker with cache version: ${cacheVersion} (${precacheAssets.length} precached asset(s))`
  );
}

const isMainModule = process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
if (isMainModule) {
  main();
}
